# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  port: <%= ENV['POSTGRES_DB_PORT'] || 5432 %>
  pool: <%= ENV.fetch('POSTGRES_DB_MAX_THREADS') { 5 } %>
  host: <%= ENV['POSTGRES_DB_HOST'] || '0.0.0.0' %>
  username: <%= ENV['POSTGRES_DB_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_DB_PASSWORD'] || 'secret' %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB_NAME'] || 'icare-dev' %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB_NAME'] || 'icare-test' %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB_NAME'] || 'icare-prod' %>
